// Refreshes test/fixtures from the backend's Postman collection, whose
// examples are real API responses (regenerated by the backend's
// `php artisan test --group=postman`).
//
//   dart run tool/sync_fixtures.dart ../bahja/docs/api/Bahga-API.postman_collection.json
import 'dart:convert';
import 'dart:io';

const _requests = {
  'Login — owner (email)': 'auth_token.json',
  'OTP — request SMS code (parents)': 'otp_request.json',
  'Me — profile, nurseries & capabilities': 'me_owner.json',
  'Me — update profile': 'me_guardian.json',
  'List children': 'children.json',
  'Get child (staff view)': 'child.json',
  'Daily attendance sheet': 'attendance_sheet.json',
  'Guardian — my pickup QR code': 'pickup_code.json',
  'Teacher — verify who is at the door': 'pickup_verify.json',
  'Guardian — issue a one-time pickup pass': 'pickup_pass_issued.json',
  'My children': 'wards.json',
  'My child — attendance history': 'ward_attendance.json',
  'My notifications (inbox)': 'notifications.json',
  'Guardian — photo consent for my child': 'photo_consent.json',
  'Teacher — post photos (multipart)': 'moment_photo.json',
  'Teacher — post a short video (multipart)': 'moment_video.json',
  "Guardian — my child's wall": 'ward_wall.json',
  'My invoice': 'invoice.json',
  'My invoices': 'invoices.json',
  'Payment methods': 'payment_methods.json',
  'Subscription & usage': 'subscription.json',
};

void main(List<String> args) {
  if (args.isEmpty) {
    stderr.writeln('usage: dart run tool/sync_fixtures.dart <path to Bahga-API.postman_collection.json>');
    exit(64);
  }

  final collection = jsonDecode(File(args.first).readAsStringSync()) as Map<String, dynamic>;
  var written = 0;

  for (final folder in (collection['item'] as List).cast<Map<String, dynamic>>()) {
    for (final request in (folder['item'] as List).cast<Map<String, dynamic>>()) {
      final file = _requests[request['name']];
      if (file == null) continue;

      final success = (request['response'] as List).cast<Map<String, dynamic>>().firstWhere((r) {
        final code = r['code'] as int;
        return code >= 200 && code < 300;
      });
      File('test/fixtures/$file').writeAsStringSync(success['body'] as String);
      written++;
    }
  }

  stdout.writeln('$written fixtures updated (errors kept as they are).');
}
